---

- hosts: all
  become: true
  pre_tasks:

  - name: install updates (RedHat-like systems)
    dnf:
      update_only: yes
      update_cache: yes
    when: ansible_distribution in ["AlmaLinux", "CentOS"]

  - name: install updates (Debian-like systems)
    apt:
      upgrade: dist
      update_cache: yes
    when: ansible_distribution in ["Debian", "Ubuntu"]

- hosts: web_servers
  become: true
  pre_tasks:

  - name: install apache and php for Debian-like systems
    apt:
      name: 
        - apache2
        - libapache2-mod-php
      state: latest
    when: ansible_distribution in ["Debian", "Ubuntu"]

  - name: install apache and php for RedHat-like systems
    dnf:
      name: 
        - httpd
        - php
      state: latest
    when: ansible_distribution in ["AlmaLinux", "CentOS"]

  tasks:

  - name: Enable and Start httpd service in RedHat-like systems
    service:
      name: httpd
      enabled: yes
      state: started
    when: ansible_distribution in ["AlmaLinux", "CentOS"]

  - name: Open httpd necessary firewall ports in RedHat-like systems
    firewalld:
      service: "{{item}}"
      state: enabled
      permanent: true
      immediate: true
    with_items:
      - http
      - https
    when: ansible_distribution in ["AlmaLinux", "CentOS"]
